### ISSUE TITLE
multiple WMS overlays in map view

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#158]
Going back and forth between start page and map page you end up with multiple WMS-overlays:

![Screenshot_20190423-092924](https://user-images.githubusercontent.com/323719/56562780-7bf4d780-65aa-11e9-9634-a7fc36676f41.png)

This might be a caching issue or that the map needs to be reloaded from cache?

Also, sometimes the map is not fully drawn, e.g. add location `Leuven`. At the bottom, part of the map is missing:

![Screenshot_20190423-093226](https://user-images.githubusercontent.com/323719/56562950-edcd2100-65aa-11e9-885c-8bce71f8691c.png)

**Comment by SpeckiJ** [comment]
This should both be fixed as of https://github.com/irceline/aq-mobile-be/commit/5ed3ee15fa04919bf5e1a99083d32040801ecd2a and https://github.com/irceline/aq-mobile-be/commit/d4250cfa4efa1c390e4b1d39a2b9c0c38d8e778a.

**Comment by opeeters** [comment]
The second issue seems to reappear with 9abe0fcef812a1ef098aa7c808540de2c29d57ae

**Comment by opeeters** [comment]
seems to be solved with: c9a0bf1
@SpeckiJ please review

**Comment by SpeckiJ** [comment]
Wierdly https://github.com/irceline/aq-mobile-be/commit/c9a0bf127a1b059be1728572f28fb1dea1ff5205 now works for me too. I could swear yesterday I needed the padding of 100px in order to prevent a grey border on the bottom, but I can't recreate it now... Works fine on my phone and in the Browser simulation.

In theory no padding should be needed so I think this solution is correct.

**Comment by opeeters** [comment]
I still had some minor issues. I changed the padding to -50 now. See af14919fd2c0925d3b210e3b35bc1225e0f5fbf4. This seems to fix it for me..
Closing the issue..
