### ISSUE TITLE
error message when REST-api is not available

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#161]
if REST-api is not available and "nearest measuring station" is activated, this is the result:

![Screenshot_20190425-105243](https://user-images.githubusercontent.com/323719/56723039-7d5c0680-6748-11e9-8ecd-af446bbad4ed.png)

A telling error message should be displayed.

**Comment by SpeckiJ** [comment]
This should be fixed with https://github.com/irceline/aq-mobile-be/commit/51038f63720054f72584e9fc2a062a2b94059457

I am reusing the Error messages from the map view. For English and German they fit pretty well - I hope French and Dutch is fine as well. Otherwise I can introduce a new translation point.

https://github.com/irceline/aq-mobile-be/blob/989544b9eecaa0d460aa1137cb98a70a433727aa/src/assets/i18n/en.json#L230
https://github.com/irceline/aq-mobile-be/blob/989544b9eecaa0d460aa1137cb98a70a433727aa/src/assets/i18n/de.json#L230
https://github.com/irceline/aq-mobile-be/blob/989544b9eecaa0d460aa1137cb98a70a433727aa/src/assets/i18n/nl.json#L230
https://github.com/irceline/aq-mobile-be/blob/989544b9eecaa0d460aa1137cb98a70a433727aa/src/assets/i18n/fr.json#L230

**Comment by opeeters** [comment]
@SpeckiJ 
This:
![Screenshot 2019-04-25 at 12 34 09](https://user-images.githubusercontent.com/323719/56730382-2a8a4b00-6758-11e9-9920-bae6e16f9f5d.png)

is maybe a bit to much redundant text.
I added a `nearest-measuring-station-panel.error` message (9d627f5)

Maybe move the message to `nearest-measuring-station-panel.component`?

**Comment by SpeckiJ** [comment]
This should be implemented as of https://github.com/irceline/aq-mobile-be/commit/a413fc0c38280e13c3005cfd21b900a922ae908e.

If one of the 5 asynchronous requests fails because the Server is unreachable (afaik the Server is the same for all), the whole panel is replaced by an error message.

**Comment by SpeckiJ** [comment]
Also needs https://github.com/irceline/aq-mobile-be/commit/87bd825d43e9f48cfaf7271148981a3aabb652a8 to be build successfully in production.

**Comment by opeeters** [comment]
Thanks!
