### ISSUE TITLE
hardware back-button misbehaves

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#167]
Steps to reproduce:
- launch app
- go to map-page either via global navigation or the shorterm/longterm panel buttons
- hit hardware back-button

Result:
all buttons in the  shorterm/longterm panel become unresponsive and the refresher of the start-page does not work anymore.

**Comment by SpeckiJ** [comment]
We have adjusted the behaviour of the back-button in https://github.com/irceline/aq-mobile-be/commit/d59cc7d409b878047a5357d5a7f86f95867d3e76.

Be careful: There were a few substantial refactorings, so further testing is necessary.

Follow-up Question:
At the moment the back-button navigates to the previous slide (if there are no modals or the info drawer, this is already handled well). Thus if you navigate via the back button twice you will get back to the page where you first pressed the button. Is this the desired behaviour? The two alternatives are

1. to store a longer history of pages (instead of only the last one)
2. always navigate to the Start-Page of the App when pressing the back-button

If we store a longer history we would need to define where to navigate once we reach the end of the history.

**Comment by opeeters** [comment]
I would always end on the start page.. And pressing the back-button (again) on the start page should close the app. Currently, you end up in an eternal loop, e.g. when you go to `map` > `diagram` > hardware back button.

1st press: close modal or info drawer, or go one back in the history
2nd press: close additional model if applicable (there are additional modals in the settings modal) or go one back in the history
3rd press: if not yet on start page go to start page
4th press: close app

With this, I think the most important cases are covered and users who use the back button to close apps don't have to go through a history which might feel a bit to long for being usefull.

**Comment by SpeckiJ** [comment]
I have adjusted the behaviour according to your suggestions in https://github.com/irceline/aq-mobile-be/commit/1d03689647b77394a0f705f9581968f8746ea536.
