### ISSUE TITLE
push notifications per user location

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#168]
In the app there is a distinction being made "official notifications" (channels `flanders`, `wallonia`, `brussels_fr` and `brussels_nl`) and automated notifications based on user locations. The automated notifications where done with a fetch from within the app will the app needed to run in the background. Since this background service consumed to much power and created other issues, this functionality was removed.

Consideration:
1) GDPR (the system should not store any information which could be linked to a user)
2) reasonable amount of messages being sent during SMOG-episodes

Proposition:
- BelAir sends only lat/long (encrypted) to our servers to be registered as push-notification channel. As soon as user location is removed by the user, so is the channel (thus we need some registration-id, but which cannot be linked to a user). 
- The user can decide per user location whether they want to receive notifications when the `BelAQI` above `5`.
- On our servers a script is run after the BelAQI-layer has successfully been updated checking all registered user-locations. If BelAQI is above `5`, an automated Push-notification is sent via a `curl` script.

**Comment by SpeckiJ** [comment]
I generally like this proposition and think it is certainly a good way to handle this feature. Some short comments:

> (thus we need some registration-id, but which cannot be linked to a user

I would propose to not even name it "registration-id", as this term imposes some sort of identifiability (an id is usually unique per device). I would rather call it "deletion key", as this is really the main purpose of the element (controlling deletion of the channel).

> BelAir sends only lat/long (encrypted) to our servers to be registered as push-notification channel

This is not completely accurate. The App autogenerates the "deletion key" (unique per location), and sends a package of `lat/lng/key` to the Server when it wants to create a channel, and the same `lat/lng/key` construct when it wants to delete the channel.
By having this key we ensure that the App can only delete channels it created itself, while still having no way of identifying an individual device in the backend as there is no correlation between the different keys.

**Note**:
What happens to channels when all app data is cleared via the Phone's Settings menu? As the app is not running we cannot send out the channel-deletion requests, so we have some dead channels. Although this is not a typical use case and should only happen very infrequently.

**Comment by SpeckiJ** [comment]
> What happens with current location?

Notifications cannot be enabled for current location.

> What happens with the topics when the App Data is cleared via the Settings Menu? What happens to the topics when the App is uninstalled?

The backend checks in Firebase whether the Notifications are still received. After a defined number of not received notifications, the subscription is cancelled. 

> How are subscriptions removed?

If a location is deleted in the app the corresponding subscription is cancelled (in case the app is offline, the unsubscription is stored and done on next startup).

> Integration into the UI

The subscription is toggled via a UI Toggle. An explaining text explains the functionality. The Notification display integrates with already existing notifications in the UI.

> Firebase topic:

The topic has the form `<lat>_<lng>`.

> Subscription Object:

The subscription is done via a `HTTP POST Request` to the API. The Subscription Object itself has the following structure (example): 

`{
	"lat": "50.878564",
	"lng": "4.655987",
	"key": "autogenerated_key_unique_per_location"
}`

The POST Request contains this Object fully encrypted using SHA256 and the API Key stored in the app. The backend decrypts the Object and then validates and parses the JSON to create the corresponding internal push to firebase.

**Comment by janschulte** [comment]
First implementation can be found in https://github.com/irceline/aq-mobile-be/tree/feature/user-location-notifications

Open issues are: 
- Endpoint to delete a registered subscription. Maybe on the same URL with an `HTTP DELETE` Request and the previously generated key `autogenerated_key_unique_per_location`
- Different HTTP codes for confirmation of `POST`and `DELETE`. 200 for success and something else on failure.
- Define a prefix for the subscription topic. Suggestion: `userlocation_<lat>_<lng>_<language>`

@opeeters Ok for you?

**Comment by opeeters** [comment]
Fine by me.
Let's change the prefix for the subscription topic to: `fcm_<lat>_<lng>_<language>`

**Comment by opeeters** [comment]
Let's reorganise the activation of the automated notifications the following way:
- remove `user-location-notifications-toggler` from `belaqi-user-location-slider`
- add `user-location-notifications-toggler` to `user-location-creation` and `modal-edit-user-location`
- add an icon to the user locations section in the settings which changes according to state, e.g. `md-notifications-off` as default and `md-notifications` with green background when notification have been activated for a specific location.

**Comment by SpeckiJ** [comment]
The toggler has been refactored in https://github.com/irceline/aq-mobile-be/commit/a9cc34aa9994cecd230c3331dd684f2ca8d3cd91.

**Comment by opeeters** [comment]
Thanks @SpeckiJ 
Not yet working 100% the way I imagined.

E.g. here it should be possible to activate the notifications (button like the `delete` and `edit`):
![Screenshot_20191015-100351](https://user-images.githubusercontent.com/323719/66812774-cfc9f300-ef33-11e9-929b-f008b06310c3.png)

When notifications are active the background should change to green. In the above example, notifications are activated for one of the two locations, but the icons don't reflect this.

The `edit location` modal is fine.

On the `create new location` modal, the notification toggle is still missing.

**Comment by SpeckiJ** [comment]
I have implemented the requested changes in https://github.com/irceline/aq-mobile-be/commit/9c84b8d22a905319210fa40ef6e4d13eb3886276 . Unfortunately the API seems to be down (i only get HTTP 500) so I can't test if everything works.

**Comment by opeeters** [comment]
Which api is giving you a 500? I don't see any issues.

**Comment by opeeters** [comment]
Let's add following enhancement of the user location notifications.. make it possible to chose an index level for the alert. 

The subscription topic should change to the following:
`fcm_<lat>_<lng>_<language>_<index>`

This level should be configurable in the settings (and during the creation of a new location, etc.).
Default level 6 

The registration should thus also be extended with an `index` element.

The logic should be, if a device last received a notification for the same index value alert, the notification should be ignored. This is to avoid notification fatigue of the users. Only when the index changes, an alert is received. Maybe something to be sorted out in firebase? When setting index: 1 the user would receive a notification whenever the index changes.

**Comment by SpeckiJ** [comment]
We have identified the two main goals. For visual clarity we have split up the problems&solutions into separate parts.

## Goal: Make sure that users only receive notifications above a certain level.

This can only be achieved by splitting up the existing topic structure into seperate subtopics, or replace it with other structures. E.g. the approach proposed earlier in the Issue would work. (creating seperate topics for each index, users subscribe to all topics with a higher index than their wanted notification level).

## Goal: Avoid that duplicate messages are shown on the device (aka show new notifications only if the air quality index has changed)

### Possible ideas:

#### 1.) Add `tag` element

The requirement could be partially solved with the `tag` element in the Notification. A new notification replaces all previous notifications with the same tag. However, this has some limitations:
 - only supported on Android
 - only applies if notifications are unread in the notification drawer (if you open a notification, you will receive a new one as soon as it is sent via the topic)

**Conclusion**: This may help in some cases (if you have unread notifications on Android) but it is no general solution.

#### 2.) Add `collapse_key` element

By specifying a `collapse_key` inside the notification FCM overwrites all messages which are not yet delivered to a device if a new notification is sent.
 - works devices that are offline and/or did not yet receive the previous notification

**Conclusion**: Useful but does not solve the issue in general manner.

#### 3.) Create dedicated topics for location+language+index

This would allow to avoid duplicate notifications on the app level. That means if the app is open, the app could handle the incoming notifications and based on the history it could ignore those which are repetitions.

However, the incoming notifications are handled first on the operating system level. Thus, if the app is not active, all incoming notifications would still be shown.

**Conclusion**: Only works with a very limited scope (if app is in foreground). All messages that are handled on the operating system level (i.e. if the app is not active) will still be shown.

#### 4.) Use of device groups + Server-side Logic

This approach would rely on an extended server-side logic. Instead of topics the devices which shall receive the same notifications will be identified by so called device groups (https://firebase.google.com/docs/cloud-messaging/android/device-group). Each group can contain up to 20 devices. By bundeling the messages we can address at one up to 500 device groups which results in 10000 devices which can be notified by one API call, the amount of API calls therefore stays reasonable.

The device groups would be organised by the the following criteria: language, location, index/notification level (similar to the proposed new topic structure). If there are more than 20 devices for the same notification criteria combination, we would create multiple device groups.

For each device group we can track which was the last notification sent to these devices. Thus, on the server-side we could control that we do not send the same notification again to these devices. For users who are new subscribers, we could create new devices groups which will be notified at the next time a notification is generated. Afterwards they would be added to the device groups containing the existing subscribers.

With this approach we could also make sure that users only receive notifications above a certain level (by including the index values in the definition of the device groups).

## Summary
For now, we only identified approach 4 as a solution to cover all requirements (only receive notifications above a certain index AND avoid duplicate notifications). However, this would require some changes on the server-side logic. @opeeters If you could provide us with the code which currently sends the Firebase messages, we could have a look at it how to enhance it to fulfill these new requirements.

**Comment by opeeters** [comment]
OK, I guess we'll script this server-side than. GDPR wise this is should be OK..

The subscription topic should change to the following:
```
{ "lat": "50.878564", "lng": "4.655987", "language": "de", "key": "uuid", "index": "level" }
```
Channel:
```
fcm_<lat>_<lng>_<language>_<index>_<uuid>
```
I'm using `gdallocationinfo` in the script. I'm reworking the script for this new approach and will share it later.

**Comment by SpeckiJ** [comment]
Thanks a lot for the feedback. This looks good. We just have one question:

In the channel definition there is now also the UUID. Shall this be the same one as in the subscription?

Originally we used the key/uuid for making sure that a user can only delete his/her own subscriptions. Thus, it was just used for the communication during the subscription/unsubscription process.

It would be great if you could shortly explain how the key/uuid shall be used in your proposed structure? If we have the same meaning of the UUID as in our previous logic, then we would have one subscription topic per device.

And just to be sure one more question: If we have a channel with a given index (e.g. index 6). Will this channel only have messages with the index 6 or will it have all messages with an index equal or greater than 6 (i.e. 6, 7, 8, 9 and 10)?

**Comment by opeeters** [comment]
Yes, indeed. The key (uuid) should be the same during registration/deletion/notification.
And yes, when a user selects index=4, the user will receive a message when the index >= 4.

I haven't tested this yet, but this is what I'm thinking of:

```sh
latest_belaqi_tiff=belaqi_20180622T120000Z.tif
now=$(date)
yesterday=$(date -d '1 days ago' +%s)
expiration=$(date -v+12H +%Y-%m-%dT%H:%M:%S%z)

psql -h $HOST -d $DB -U $USER -c "SELECT * FROM fcm_channel;" \
--no-align \
-t \
--field-separator ' ' \
| while read lat lng language index key last_message last_index; do
value=$(gdallocationinfo -wgs84 $latest_belaqi_tiff $lng $lat | grep Value | cut -d' ' -f6)
last_message_unix=$(date -d $last_message +%s)
if [ "$value" >= "$index" && "$value" != "$last_index" ] || [ "$value" = "$index" && $last_message_unix <= $yesterday ]; then
  channel=fcm_$lat'_'$lng'_'$language'_'$index'_'$key
  curl -X POST https://fcm.googleapis.com/fcm/send -i -H "Content-type: application/json" -H "Authorization: key='$fcm_key'" -d "{
  \"notification\": {
      \"title\": \"BelAQI is '$value'\",
      \"body\": \"Not all is well\",
      \"sound\": \"default\",
      \"icon\": \"icon\",
      \"subtitle\": \"BelAQI is '$value', all is not well.\"
  },
  \"data\": {
    \"title\": \"BelAQI is '$value'\",
    \"body\": \"BelAQI is '$value', all is not well\",
    \"topic\": \"'$channel'\",
    \"expiration\": \"'$expiration'\"
  },
  \"to\": \"/topics/'$channel'\",
  \"priority\": \"high\",
  \"restricted_package_name\": \"\"
}"
psql -h $HOST -d $DB -U $USER -c "UPDATE fcm_channel SET last_index=$value, SET last_message=$now WHERE key=$key;"
fi
done
```

**Comment by SpeckiJ** [comment]
Thanks for the script - it definitely helped in understanding the approach.

One Comment: With the presence of the unique <uuid> in the topic we do not need the elements <lat>, <lon>, <language> and <index> anymore, as the channel is specific to a device. I think it would be more clean if we left out these superflous strings from the topic name to not confuse ourselves when looking at them later on.

I therefore would propose just simplifying the topic to:

`fcm_<uuid>`

**Comment by opeeters** [comment]
OK, good idea. One comment though, the `uuid` is unique to a registration/chennel, not a device. One device can have multiple registrations.

In the case that a user uninstalls the app, how will we delete obsolete channels?
Monitoring whether messages are actually received via FB?

**Comment by SpeckiJ** [comment]
I have added a first implementation that adopts the new topic name and allows the user to set an alert level in https://github.com/irceline/aq-mobile-be/commit/59a653d6b62100a25d7670f39c2543934d7d57e2

Regarding the deletion of "invalid" subscriptions (app uninstalled) - we will look into that. As we have no processing time, and therefore cannot run any code when the user uninstalls the app, it will have to be a server-side solution, e.g. a regular "ping" request from the client upon App start refreshing the subscription. If no ping is received for a defined amount of time (e.g. 1 month) a "please open the app or notifications will be disabled" message could be send and the subscription deleted 1 week later if this did not happen.

**Comment by SpeckiJ** [comment]
https://github.com/irceline/aq-mobile-be/blob/d0c85088fb39601c3c891408703424ecefd2b89d/src/app/components/notification-panel/notification-panel.component.ts#L44 still needs adjustment as lat and lon are not available from the topic anymore.

**Comment by SpeckiJ** [comment]
> https://github.com/irceline/aq-mobile-be/blob/d0c85088fb39601c3c891408703424ecefd2b89d/src/app/components/notification-panel/notification-panel.component.ts#L44
> still needs adjustment as lat and lon are not available from the topic anymore.

done in https://github.com/irceline/aq-mobile-be/commit/18c2671818df07cb174295d6f33d891f8edd58e4

**Comment by janschulte** [comment]
Where do you want to see the notifications regarding the location? Also in the popup behind the exclamation mark on the main screen?

**Comment by opeeters** [comment]
Yes, that would be a good place for now.

**Comment by janschulte** [comment]
The push notifications for user location are implemented now in branch: [feature/52n-user-location-notification](https://github.com/irceline/aq-mobile-be/tree/feature/52n-user-location-notification)

**Comment by opeeters** [comment]
also implemented for v2 (cf feature/52n-user-location-notification)
