### ISSUE TITLE
Add current location update to refresh (start page)

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#170]
There still seem to be some issues with the update of the current location. When being on the move it takes to long for the app to get the new current location (even when other apps are already using it). Probably related to the location age being used currently. 

Maybe add some additional location rule to the refresh (pulling start page down)?

**Comment by SpeckiJ** [comment]
We are currently caching the Location for 5 Minutes before we refresh it:

https://github.com/irceline/aq-mobile-be/blob/58565d3e4f3a84fcfdba0fba6950840c1e3b7014/src/app/services/locate/locate.service.ts#L19

See the docs here: https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions/maximumAge

**Comment by SpeckiJ** [comment]
This should be fixed with https://github.com/irceline/aq-mobile-be/commit/aed4b277cac88e3fb75ef08c4f63819fa6c6dd3d

Reason for the bug was invalid cache key generation. We were already triggering a refresh of the location when swiping down on the start page, but we reused an old cache key and therefore stopped the refresh when we already found a cached version.

This has the same root cause as #165 - a change in the serialization behaviour of Maps introduced with https://github.com/irceline/aq-mobile-be/commit/a5a21d49b187ecb30dcd7b432736d41a938c8c48

**Comment by opeeters** [comment]
Works perfectly now
