### ISSUE TITLE
production build error: Property 'autocompleteService' is protected

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#199]
Running `ionic cordova build android --prod --release` on `master` ends with the following error:
```
ERROR in src/app/components/mobile-geosearch-control/mobile-geosearch-control.component.html(7,31): : Property 'autocompleteService' is protected and only accessible within class 'MobileGeosearchControlComponent' and its subclasses.

[ERROR] An error occurred while running subprocess ng.
```
A dev build terminates and the app installs fine on device..

**Comment by SpeckiJ** [comment]
The initial error is easily fixed, but there are underlying issues.

It seems that the ionic4-auto-complete has some dependency incompatibilities when trying to build with `--prod` flag set. Some code optimization inside angular-dev throws build errors that cannot be resolved automatically.

I will look into it and upate the Issue when I find the root cause

**Comment by opeeters** [comment]
@SpeckiJ 
Can you commit the fix for the initial error, please. I'll have a look if I can find a fix with the one or other version pinning..

**Comment by janschulte** [comment]
@opeeters I am on it now and I have hopefully found a dirty quick fix for the mentioned incompatibilities by @SpeckiJ.

Due to another appointment coming up for me now I can hopefully provide you the fix in the afternoon.

**Comment by janschulte** [comment]
@opeeters The build should run now...

**Comment by opeeters** [comment]
@janschulte Thanks allot. The build terminates successfully now. I'll put the upgrade to Angular 8 in new issue, but this is for after release 1.0.1.
