### ISSUE TITLE
Relabel "Current Location" Button to "Closest Measuring Station"

### ISSUE THREAD

**Issue by SpeckiJ** [irceline/aq-mobile-be#239]
It is currently very confusing that you click on 'Current Location' and get a totally different city added to the list, and not your actual physical location. I would propose relabeling this button something more appropiate like "Closest Measuring Station", to reflect what it actually does.

Currently the 'Current Location' Button in the Settings Menu simply takes the closest measuring station and adds it to the location list. In the List there is no indication that this location is of type 'current', and it is handled the same as all other locations in the code.

I have already removed the 'current' type from the UserLocation in https://github.com/irceline/aq-mobile-be/commit/ccce24ac6d503cefa0b355d9fb02f44080cc50e5 as it led to confusion in the code and was not used anywhere. If this is needed in the future the `UserLocation->type` can simply be extended again (e.g. once live updating locations are added).

**Comment by opeeters** [comment]
I agree that the current flow is very confusing. 

It's not the closest measuring station which is selected when selecting 'Current Location'. See [/src/assets/locations.json](/src/assets/locations.json). When 'current location` is selected, a position of the device is establish via the native location service. Via a distance matrix, the closest lat/long from the [/src/assets/locations.json](/src/assets/locations.json) is matched with the established location. The lat/long in the list is the centroid of the relevant administrative unit (commune or city - the LAU-level, formerly known as NUTS4 if I'm not mistaken).

We need to thoroughly revise how a user location is registered. Since this is a fundamental part of how the app established the local air quality for the user this needs to fit well with how we communicate about the app. 

I'm busy consulting all concerned stakeholders. I'll get back to this and self-assign it for the time-being. Thanks for bringing it up ;-)

**Comment by opeeters** [comment]
Let's do the following:
- in the settings, add a little map icon per location where the user can refine the location to their exact location (drage and drop + OSM-Nominatim) in a pop-up. Add a confirmation button (e.g. `save changes`) when location is changed.
- for the onboarding, setting a location has to always work (with or without network or a recent enough last known location). Maybe a combination of the current list of communes and OSM-Nominatim? The auto-complete has higher priority in giving suggestions, but OSM-Nominatim adds suggestions if network is available, or something similar.

**Comment by janschulte** [comment]
Some questions from my side: 
- do you plan to have a self deployed nominatim service?
- same for the wms base layer (currently a layer from stadiamaps is configured for the map - [see here](https://github.com/irceline/aq-mobile-be/blob/52n-v2-upgrade/src/app/v2/components/map-component/map.component.ts#L64)) Will you use stadia maps also in production? Or do you use your own BaseLayer Service?
- some clarification for the onboarding flow. When the user chooses `current location` the device get's a position, with this position it tries to get an adress of the nominatim service. Is there a result of the service, it will be used, otherwise the nearest result of the locations.json is used? The autocomplete field is currently only based on the input of the user.

**Comment by opeeters** [comment]
- We have a proto-type tileserver running in our infrastructure. To add a nominatim service (e.g. https://nominatim.org/ or a service with auto-complete, e.g.: [pelias](https://github.com/pelias/pelias), [gisgraphy](https://www.gisgraphy.com/index.php) or [OSMNames](https://osmnames.org/) - any suggestions more than welcome) was not yet the ambition, but we'll look into it. 
- Should all else fail we might use the stadia maps, but that depends on whether they are flexible enough with their subscription plans.
- this sequence sounds good.

**Comment by janschulte** [comment]
How should Locations outside of Belgium be handled? You can get one by device location or by edit popup.

**Comment by janschulte** [comment]
Do you have a geojson for belgium, then I can used it to check if the location in inside belgium. If the location is outside, I can revert the edition or creation of the location.

**Comment by opeeters** [comment]
> Do you have a geojson for belgium, then I can used it to check if the location in inside belgium. If the location is outside, I can revert the edition or creation of the location.

see 2ead273c00c88a3f4ceac71e5ad818882d4609d8
The file has a rather large footprint. Maybe apply some simplification of the feature?

**Comment by janschulte** [comment]
Thanks, it should have the bounds, which you also use on server side to generate the layers and the belaqi calculation. But maybe this is no big deal, because it is shipped with the apk. I will integrate the evaluation and check the performance.

**Comment by janschulte** [comment]
Done and works well in my opinion.

**Comment by opeeters** [comment]
Yea, works very intuitive. But I will still add a tooltip to the map view.

I cannot trigger the intro anymore. Also after clearing all app data.

**Comment by opeeters** [comment]
@janschulte 
Instead of the quick-fix of setting random location added to 0 (cf 86843aad5681b60fe4f7c56423c53d265174fd64), this function should redirect the user to the tab in the intro where the user is asked to set a location.

**Comment by opeeters** [comment]
On the tab for setting the location during onboarding, a button should appear as soon as the user has chosen a location, inviting the user to fine-tune on a map. This should take the user to the same map editor where the icon can be moved.
