### ISSUE TITLE
View in detail not returning to default after choosing pollutant and closing

### ISSUE THREAD

**Issue by ffierens** [irceline/aq-mobile-be#279]
After choosing a pollutant using "View in detail" and closing the "View in detail" again, the app is not returning to the default config (=the option with all pollutants). It is necessary to close and reopen the app to get the list of all pollutants in the "View in detail" again.
(version 1.7.9)

**Comment by bieblebrox** [comment]
It should be possible to return to the list by simply pressing the back button (left pointing arrow), as you can see in the video below



https://user-images.githubusercontent.com/53826760/117012655-7715a300-acef-11eb-9d2e-e8ea1dac674b.mp4

**Comment by opeeters** [comment]
Different behaviour on Samsung A50 (Android 11), I'm afraid. When you click the back button on the map-tab, the app closes..

**Comment by opeeters** [comment]
Maybe were looking at different things here. @ffierens is not revering to the back button on the tab:
![image](https://user-images.githubusercontent.com/323719/117117276-a67bec80-ad8f-11eb-9b8f-662500e5dffd.png)

But rather the system back-button (Android specific).  I think this issue is rather something for @janschulte or @SpeckiJ But we had this issue before (cf #224). Maybe some code was accidentally removed? I can't find the `storeLastNavigation` function I was revering to anymore in the code. But it's maybe rather related to `newRoute` and `NavigationEnd`?

Steps to reproduce:
- open `view in detail`
- chose e.g. the BelAQI
- click Android system back-button

Result:
- App closes
From a user perspective you would expect the that you would first go back to the initial `view in detail` and on second click back to the landing tab.

The system back button works well in the info-tab, menu, feedback and long-term tab

**Comment by bieblebrox** [comment]
Back button events are now caught and connected to pulltab
