### ISSUE TITLE
Long term screen not loading anymore

### ISSUE THREAD

**Issue by ffierens** [irceline/aq-mobile-be#300]
The long term screen does not show the long term data
![image](https://user-images.githubusercontent.com/12494775/146517124-3ffe650f-d05e-4971-b6c2-8d41a3cfb8ae.png)

**Comment by opeeters** [comment]
This is a legacy issue. In the past we decided to use rioifdm and not atmostreet for the long term in the app (to avoid bizar conclusions based on comparing apples with oranges since there is no 5 year sequence yet of comparable atmostreet versions and comparing years for close-to-street-canyon locations is also not always a good idea). 
This year you apparently published only atmostreet versions (accept for o3). Hence, the eternal spinning wheel of joy.. it's impossible to find something that does not exist.
As long as the bar chart comparing years remains on the longterm tab, it would still be better to stick with rioifdm, no?

**Comment by ffierens** [comment]
solved, back to 2019 as last ifdm year
